"""empty message

Revision ID: 1268475ae95f
Revises: 141c46bf8842
Create Date: 2024-02-13 12:23:48.106318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1268475ae95f'
down_revision = '141c46bf8842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Service')
    op.drop_table('Cars')
    op.drop_table('Sales')
    op.drop_table('Customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('Customer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Car', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Invoice', sa.INTEGER(), server_default=sa.text('nextval(\'"Customer_Invoice_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('SVC_Ticket', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Car'], ['Cars.Car'], name='FK_Customer.Car')
    )
    op.create_table('Sales',
    sa.Column('Salesperson', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Invoice', sa.INTEGER(), server_default=sa.text('nextval(\'"Sales_Invoice_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Car', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Car'], ['Cars.Car'], name='FK_Sales.Car')
    )
    op.create_table('Cars',
    sa.Column('Invoice', sa.INTEGER(), server_default=sa.text('nextval(\'"Cars_Invoice_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Car', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Salesperson', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('SVC_History', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Car', name='Cars_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Service',
    sa.Column('Mechanic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Car', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('SVC_History', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('SVC_Ticket', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Parts', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Car'], ['Cars.Car'], name='FK_Service.Car')
    )
    # ### end Alembic commands ###
