"""empty message

Revision ID: 90be45a69eb5
Revises: 9ec5623afcaa
Create Date: 2024-02-13 16:19:15.974061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90be45a69eb5'
down_revision = '9ec5623afcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car__dealership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=200), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car__dealership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
